<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE codelean [
    <!ELEMENT codelean (to, form, subject, message)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT form (#PCDATA)>
    <!ELEMENT subject (#PCDATA)>
    <!ELEMENT message (#PCDATA)>
]>

<codelean>
    <to>My Readers</to>
    <form>ThiDK</form>
    <subject>A Message to my readers</subject>
    <message>Welcome to codelean.vn</message>
</codelean>

